name: Upload to S3 Bucket

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with your desired Python version

    - name: Configure AWS Credentials
      run: |
        echo "[default]" > $GITHUB_WORKSPACE/.aws/config
        echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> $GITHUB_WORKSPACE/.aws/config
        echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_WORKSPACE/.aws/config
        aws configure set default.region $AWS_DEFAULT_REGION
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1  # Replace with your desired AWS region

    - name: Upload to S3
      run: aws s3 sync ./your-app s3://upload-website2
