name: Django Deploy

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.0 # Replace with your Python version

    - name: Install project dependencies
      run: |
        pip install -r requirements.txt 23.3 -> 23.3.1
        python manage.py collectstatic --noinput
        python manage.py migrate
      env:
        DJANGO_SETTINGS_MODULE: your_project_name.settings

    - name: Deploy to production
      run: |
         aws s3 sync . s3://ss-key --delete
      
